language: python

python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -rrequirements-test.txt
  - pip install coveralls

script:
  #- if [[ $TRAVIS_PYTHON_VERSION = '2.6' || $TRAVIS_PYTHON_VERSION = '2.7' ]]; then
  #      pytest tests.py --cov pyprofmem;
  #  else
  #      py.test tests.py --cov pyprofmem;
  #  fi
  - py.test tests.py --cov pyprofmem;

after_success:
  - coveralls