language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -rrequirements-test.txt
  - pip install coveralls

script:
  - if [[ $TRAVIS_PYTHON_VERSION = '2.6' || $TRAVIS_PYTHON_VERSION = '2.7' ]]; then
        py.test tests.py;
    else
        pytest tests.py;
    fi

after_success:
  - coveralls